spring.application.name=school-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/school_management_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=14092004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
app.jwt.secret=9a4f2c8d3b7a1e5f8c6b4d2e0a1b3c5e7f9a8b6c5d4e3f2g1h0j9k8l7m6n5o4p
app.jwt.expiration-ms=86400000
